[build]
  publish = "dist"
  command = "npm run build:local"
  functions = "functions"

# Production context
[context.production]
  environment = { NODE_VERSION = "20.9.0" }
  command = "npm run build:local"

# Deploy Preview context
[context.deploy-preview]
  environment = { NODE_VERSION = "20.9.0" }
  command = "npm run build:local"

# Branch deploy context
[context.branch-deploy]
  environment = { NODE_VERSION = "20.9.0" }
  command = "npm run build:local"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Updated CSP to allow for Web Audio API, canvas functionality, and web components
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' data: blob:; connect-src 'self'; worker-src 'self' blob:; manifest-src 'self'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# PWA headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "max-age=0,no-cache,no-store,must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "max-age=3600"

# Audio files optimization
[[headers]]
  for = "/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.wav"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize asset caching
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Web Components assets
[[headers]]
  for = "/components/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Handle redirects
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = true

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200
  force = true

[[redirects]]
  from = "/poetry"
  to = "/poetry.html"
  status = 200
  force = true

[[redirects]]
  from = "/thoughts"
  to = "/thoughts.html"
  status = 200
  force = true

[[redirects]]
  from = "/experiments"
  to = "/experiments.html"
  status = 200
  force = true

[[redirects]]
  from = "/memory-wall"
  to = "/memory-wall.html"
  status = 200
  force = true

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
  force = true

# SPA fallback - must be last redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Set correct content type for XML files
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"

# RSS feed
[[headers]]
  for = "/feed.xml"
  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"

[dev]
  port = 3000
  publish = "www"
  framework = "#static"
  targetPort = 3000